import { Channel, ContentType, MessageStatus, MessageType } from '@/types';

export const conversation = {
  senderName: 'Leo Das',
  senderThumbnail: 'https://i.pravatar.cc/300',
  id: 250,
  accountId: 1,
  isTyping: false,
  timestamp: 1732205198,
  firstReplyCreatedAt: 1732118959,
  inbox: {
    id: 1,
    avatarUrl: 'https://example.com/avatar.png',
    channelId: 1,
    name: 'Test Inbox',
    channelType: 'Channel::FacebookPage' as Channel,
    phoneNumber: '+1234567890',
    medium: 'web',
  },
  lastMessage: {
    id: 2346,
    content:
      'Hi there, I accidentally purchased the wrong item. Can I cancel the order and get a refund?',
    attachments: [],
    contentType: 'text' as ContentType,
    conversationId: 250,
    createdAt: 1732205198,
    from: 'John Doe',
    echoId: '123',
    inboxId: 1,
    messageType: 0 as MessageType,
    private: false,
    sourceChannel: 'Channel::FacebookPage' as Channel,
    sourceId: null,
    status: 'sent' as MessageStatus,
    lastNonActivityMessage: null,
    conversation: null,
  },
  slaPolicyId: null,
  appliedSla: null,
  additionalAttributes: {},
  appliedSlaConversationDetails: {},
  labels: [],
  allLabels: [
    { color: '#28AD21', description: '', id: 1, showOnSidebar: true, title: 'billing' },
    { color: '#9C5311', description: '', id: 2, showOnSidebar: true, title: 'lead' },
    { color: '#F85DE2', description: '', id: 3, showOnSidebar: true, title: 'premium-customer' },
    { color: '#8F6EF2', description: '', id: 4, showOnSidebar: true, title: 'software' },
    { color: '#A53326', description: '', id: 5, showOnSidebar: true, title: 'delivery' },
  ],
};
