export const INSTAGRAM_MESSAGES = [
  {
    id: 25281800,
    content: 'cwtestinglocal mentioned you in the story: ',
    inbox_id: 27355,
    conversation_id: 23731,
    message_type: 0,
    content_type: 'text',
    status: 'sent',
    content_attributes: {
      story_sender: 'cwtestinglocal',
      story_id: '17889220763812855',
      image_type: 'story_mention',
    },
    created_at: 1692765935,
    private: false,
    source_id:
      'aWdfZAG1faXRlbToxOklHTWVzc2FnZAUlEOjE3ODQxNDQ3NTU5OTYxMzk4OjM0MDI4MjM2Njg0MTcxMDMwMDk0OTEyODIyODExNDI0MDczNjkxMTozMTE5MjcwODk3OTU5MTM2NDg4NTg2OTU1NTEzOTczOTY0OAZDZD',
    sender: {
      additional_attributes: {
        social_profiles: {
          instagram: 'cwtestinglocal',
        },
      },
      custom_attributes: {},
      email: null,
      id: 53375128,
      identifier: null,
      name: 'Jane Doe',
      phone_number: null,
      thumbnail: '',
      type: 'contact',
    },
    attachments: [
      {
        id: 2053726,
        message_id: 25281804,
        file_type: 'image',
        account_id: 1,
        extension: null,
        data_url: 'https://videos.pexels.com/video-files/7722989/7722989-uhd_1440_2560_25fps.mp4',
        thumb_url: 'https://videos.pexels.com/video-files/7722989/7722989-uhd_1440_2560_25fps.mp4',
        file_size: 376973,
        width: 1179,
        height: 2096,
      },
    ],
  },
  {
    id: 26433214,
    content: 'Hey Jane, I am Jane',
    inbox_id: 27355,
    conversation_id: 26942,
    message_type: 1,
    content_type: 'text',
    status: 'sent',
    content_attributes: {},
    created_at: 1692765959,
    private: false,
    source_id:
      'aWdfZAG1faXRlbToxOklHTWVzc2FnZAUlEOjE3ODQxNDQ3NTU5OTYxMzk4OjM0MDI4MjM2Njg0MTcxMDMwMTI0NDI1OTM2Nzg4MDM2MjUyNjUwNjozMTIyNjAyMDQzOTQ5ODg4NzY4NTUxMTc5Mzk5MjUzMTk2OAZDZD',
    sender: {
      id: 1,
      name: 'Jane Doe',
      available_name: 'Jane Doe',
      avatar_url: 'https://xsgames.co/randomusers/assets/avatars/pixel/22.jpg',
      type: 'user',
      availability_status: 'online',
      thumbnail: 'https://xsgames.co/randomusers/assets/avatars/pixel/22.jpg',
    },
  },
  {
    id: 89088799,
    content: null,
    account_id: 1,
    inbox_id: 27355,
    conversation_id: 26942,
    message_type: 0,
    created_at: 1733387803,
    updated_at: '2024-12-05T08:36:43.200Z',
    private: false,
    status: 'sent',
    source_id:
      'aWdfZAG1faXRlbToxOklHTWVzc2FnZAUlEOjE3ODQxNDQ3NTU5OTYxMzk4OjM0MDI4MjM2Njg0MTcxMDMwMTI0NDI1OTM2Nzg4MDM2MjUyNjUwNjozMTk3NTM2MTE2ODI4MTc0MDMzMDA3NzAwNzkxNTI1Mzc2MAZDZD',
    content_type: 'text',
    content_attributes: {
      in_reply_to_external_id: null,
    },
    sender_type: 'Contact',
    sender_id: 70222869,
    external_source_ids: {},
    additional_attributes: {},
    processed_message_content: null,
    sentiment: {},
    conversation: {
      assignee_id: 1,
      unread_count: 1,
      last_activity_at: 1733387803,
      contact_inbox: {
        source_id: '6448268745221611',
      },
    },
    attachments: [
      {
        id: 7141507,
        message_id: 89088799,
        file_type: 'ig_reel',
        account_id: 1,
        extension: null,
        data_url: 'https://videos.pexels.com/video-files/2023708/2023708-hd_720_1280_30fps.mp4',
        thumb_url: 'https://videos.pexels.com/video-files/2023708/2023708-hd_720_1280_30fps.mp4',
        file_size: 2464867,
        width: null,
        height: null,
      },
    ],
    sender: {
      additional_attributes: {
        social_profiles: {
          instagram: 'cwtestinglocal',
        },
      },
      custom_attributes: {},
      email: null,
      id: 70222869,
      identifier: null,
      name: 'Jane Doe',
      phone_number: null,
      thumbnail: '',
      type: 'contact',
    },
  },
  {
    id: 89129832,
    content: null,
    inbox_id: 27355,
    conversation_id: 26942,
    message_type: 0,
    content_type: 'text',
    status: 'sent',
    content_attributes: {
      in_reply_to_external_id: null,
      is_unsupported: true,
    },
    created_at: 1733399171,
    private: false,
    source_id:
      'aWdfZAG1faXRlbToxOklHTWVzc2FnZAUlEOjE3ODQxNDQ3NTU5OTYxMzk4OjM0MDI4MjM2Njg0MTcxMDMwMTI0NDI1OTM2Nzg4MDM2MjUyNjUwNjozMTk3NTU3MDg2NDAzNzQ0ODY5NjA0NDc2MzA5MjA5MDg4MAZDZD',
    sender: {
      additional_attributes: {
        social_profiles: {
          instagram: 'cwtestinglocal',
        },
      },
      custom_attributes: {},
      email: null,
      id: 70222869,
      identifier: null,
      name: 'Jane Doe',
      phone_number: null,
      thumbnail: '',
      type: 'contact',
    },
  },
];
