export const TEXT_ONLY = [
  {
    id: 5313,
    content: 'Hello, hi there',
    account_id: 2,
    inbox_id: 486,
    conversation_id: 1016,
    message_type: 0,
    created_at: 1732711025,
    updated_at: '2024-11-27T12:37:05.439Z',
    private: false,
    status: 'sent',
    source_id: null,
    content_type: 'text',
    content_attributes: {
      in_reply_to: null,
    },
    sender_type: 'Contact',
    sender_id: 599,
    external_source_ids: {},
    additional_attributes: {},
    processed_message_content: 'This is perfect, thanks a lot. Let me know the next steps',
    sentiment: {},
    conversation: {
      assignee_id: 1,
      unread_count: 1,
      last_activity_at: 1732711025,
      contact_inbox: {
        source_id: 'f42d4630-7c41-4af3-bbc7-7c43e2aa2fc7',
      },
    },
    sender: {
      additional_attributes: {
        created_at_ip: '::1',
      },
      custom_attributes: {},
      email: 'anthony@example.com',
      id: 599,
      identifier: null,
      name: 'anthony',
      phone_number: null,
      thumbnail: '',
      type: 'contact',
    },
  },
  {
    id: 5314,
    content: 'Okay',
    account_id: 2,
    inbox_id: 486,
    conversation_id: 1016,
    message_type: 0,
    created_at: 1732711025,
    updated_at: '2024-11-27T12:37:05.439Z',
    private: false,
    status: 'sent',
    source_id: null,
    content_type: 'text',
    content_attributes: {
      in_reply_to: null,
    },
    sender_type: 'Contact',
    sender_id: 599,
    external_source_ids: {},
    additional_attributes: {},
    processed_message_content: 'This is perfect, thanks a lot. Let me know the next steps',
    sentiment: {},
    conversation: {
      assignee_id: 1,
      unread_count: 1,
      last_activity_at: 1732711025,
      contact_inbox: {
        source_id: 'f42d4630-7c41-4af3-bbc7-7c43e2aa2fc7',
      },
    },
    sender: {
      additional_attributes: {
        created_at_ip: '::1',
      },
      custom_attributes: {},
      email: 'anthony@example.com',
      id: 599,
      identifier: null,
      name: 'anthony',
      phone_number: null,
      thumbnail: '',
      type: 'contact',
    },
  },
  {
    id: 5315,
    content: 'haeea',
    account_id: 2,
    inbox_id: 486,
    conversation_id: 1016,
    message_type: 0,
    created_at: 1732711025,
    updated_at: '2024-11-27T12:37:05.439Z',
    private: false,
    status: 'sent',
    source_id: null,
    content_type: 'text',
    content_attributes: {
      in_reply_to: null,
    },
    sender_type: 'Contact',
    sender_id: 599,
    external_source_ids: {},
    additional_attributes: {},
    processed_message_content: 'This is perfect, thanks a lot. Let me know the next steps',
    sentiment: {},
    conversation: {
      assignee_id: 1,
      unread_count: 1,
      last_activity_at: 1732711025,
      contact_inbox: {
        source_id: 'f42d4630-7c41-4af3-bbc7-7c43e2aa2fc7',
      },
    },
    sender: {
      additional_attributes: {
        created_at_ip: '::1',
      },
      custom_attributes: {},
      email: 'anthony@example.com',
      id: 599,
      identifier: null,
      name: 'anthony',
      phone_number: null,
      thumbnail: '',
      type: 'contact',
    },
  },
  {
    id: 5316,
    content: 'Layout shift happens',
    account_id: 2,
    inbox_id: 486,
    conversation_id: 1016,
    message_type: 0,
    created_at: 1732711025,
    updated_at: '2024-11-27T12:37:05.439Z',
    private: false,
    status: 'sent',
    source_id: null,
    content_type: 'text',
    content_attributes: {
      in_reply_to: null,
    },
    sender_type: 'Contact',
    sender_id: 599,
    external_source_ids: {},
    additional_attributes: {},
    processed_message_content: 'This is perfect, thanks a lot. Let me know the next steps',
    sentiment: {},
    conversation: {
      assignee_id: 1,
      unread_count: 1,
      last_activity_at: 1732711025,
      contact_inbox: {
        source_id: 'f42d4630-7c41-4af3-bbc7-7c43e2aa2fc7',
      },
    },
    sender: {
      additional_attributes: {
        created_at_ip: '::1',
      },
      custom_attributes: {},
      email: 'anthony@example.com',
      id: 599,
      identifier: null,
      name: 'anthony',
      phone_number: null,
      thumbnail: '',
      type: 'contact',
    },
  },
];
