export const SET_LOCALE = 'SET_LOCALE';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SET_AUTH_HEADER = 'SET_AUTH_HEADER';

export const GET_INBOX = 'GET_INBOX';
export const GET_INBOX_SUCCESS = 'GET_INBOX_SUCCESS';
export const GET_INBOX_ERROR = 'GET_INBOX_ERROR';

export const SET_INBOX = 'SET_INBOX';

export const GET_CONVERSATION = 'GET_CONVERSATION';
export const GET_CONVERSATION_SUCCESS = 'GET_CONVERSATION_SUCCESS';
export const GET_CONVERSATION_ERROR = 'GET_CONVERSATION_ERROR';
export const SET_CONVERSATION_STATUS = 'SET_CONVERSATION_STATUS';

export const USER_LOGOUT = 'USER_LOGOUT';
