name: Create production builds

on:
  push:
    branches: ['main']

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: production

  build_ios:
    type: build
    params:
      platform: ios
      profile: production

  submit_android:
    type: submit
    params:
      platform: android
      profile: production
      build_id: ${{ needs.build_android.outputs.build_id }}
    needs:
      - build_android
  
  submit_ios:
    type: submit
    params:
      platform: ios
      profile: production
      build_id: ${{ needs.build_ios.outputs.build_id }}
    needs:
      - build_ios
