default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Beta(Internal)"
  lane :beta_internal do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(
      track: 'internal'
    )
  end

  desc "Submit a new Beta Build to Beta(Open)"
  lane :beta_open do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(track: 'beta')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
